---
# Source: docker-registry/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/registry/scaut-v2-dev-secrets-manager-registry
  dataFrom:
    - scaut-v2-dev/registry/docker-registry-secret