apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-nextcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcloud-rsh
subjects:
  - kind: ServiceAccount
    name: sync
    namespace: temporary-data-warehouse