apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-rsh
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "*"