apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mysql-root-password
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/nextcloud/scaut-v2-dev-secrets-manager-nextcloud
  dataFrom:
    - scaut-v2-dev/nextcloud/nextcloud-mysql-root

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mysql-user
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/nextcloud/scaut-v2-dev-secrets-manager-nextcloud
  dataFrom:
    - scaut-v2-dev/nextcloud/nextcloud-mysql-user

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/nextcloud/scaut-v2-dev-secrets-manager-nextcloud
  dataFrom:
    - scaut-v2-dev/nextcloud/nextcloud-admin