apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pypi-auth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/openshift-build/scaut-v2-dev-secrets-manager-pypi
  dataFrom:
    - scaut-v2-dev/openshift-build/pypi-auth