apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-namespaces
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-external-secrets
rules:
  - apiGroups:
      - kubernetes-client.io
    resources:
      - externalsecrets
    verbs:
      - "*"