apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 25Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi