apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-manage-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-pods
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-manage-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-namespaces
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-manage-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-external-secrets
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default