apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-oauth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/openshift-build/scaut-v2-dev-secrets-manager-jenkins
  dataFrom:
    - scaut-v2-dev/openshift-build/jenkins-google-oauth

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ssh-privatekey
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/openshift-build/scaut-v2-dev-secrets-manager-jenkins
  dataFrom:
    - scaut-v2-dev/openshift-build/jenkins-ssh-privatekey

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pypi-config
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/openshift-build/scaut-v2-dev-secrets-manager-jenkins
  dataFrom:
    - scaut-v2-dev/openshift-build/jenkins-pypi-config

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: internal-registry
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/scaut-v2-dev-secrets-manager-registry-config
  dataFrom:
    - scaut-v2-dev/docker-registry-config
  template: 
   type: kubernetes.io/dockerconfigjson

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/pull-request/scaut-v2-dev-secrets-manager-pull-request-postgresql
  dataFrom:
    - scaut-v2-dev/pull-request/postgresql