apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-oauth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/openshift-build/scaut-v2-dev-secrets-manager-jenkins
  dataFrom:
    - scaut-v2-dev/openshift-build/jenkins-google-oauth